entitlements/strictly-audited/admin.txt:
  sha256sum: bf05869dd6172715f9fe952a01ca8702c90a1991d2755a68d698207e954d094b
  format:
    - txt
  reviews:
    enabled: true
    labels:
      - Periodic Audit
    days: 182
    strategy: manager
    title: Admin access
