<%-
ENV["BUNDLE_GEMFILE"] = File.expand_path("../../Gemfile", File.dirname(__FILE__))
require "bundler/setup"
require "entitlements"

# require entitlements plugins here
require "entitlements/backend/github_org"
require "entitlements/backend/github_team"
require "entitlements/service/github"
-%>
---
backends:
  dockerized-ldap:
    ldap_binddn: "cn=admin,dc=example,dc=org"
    ldap_bindpw: "admin"
    ldap_uri: "ldaps://127.0.0.1"
    disable_ssl_verification: true
    person_dn_format: uid=%KEY%,ou=People,dc=example,dc=org
    type: ldap
configuration_path: ../
extras:
  ldap_group: {}

groups:
  dummy-ou:
    type: dummy
  dummy-ou-renamed:
    type: dummy
    dir: dummy-ou-special
  entitlements:
    backend: dockerized-ldap
    base: ou=Entitlements,ou=Groups,dc=example,dc=org
  entitlements/strictly-audited:
    backend: dockerized-ldap
    base: ou=strictly-audited,ou=Entitlements,ou=Groups,dc=example,dc=org
    dir: entitlements/strictly-audited
    create_if_missing: true
  github.com/danhoerst-test/teams:
    addr: <%= ENV["GITHUB_API_BASE"] %>
    base: ou=teams,ou=github,ou=GitHub,dc=github,dc=com
    dir: github.com/danhoerst-test/org
    org: danhoerst-test
    token: <%= ENV["GITHUB_ORG_TOKEN"] %>
    type: "github_org"
people:
  ldap:
    type: ldap
    config:
      base: ou=People,dc=example,dc=org
      ldap_binddn: "cn=admin,dc=example,dc=org"
      ldap_bindpw: "admin"
      ldap_uri: "ldaps://127.0.0.1"
      disable_ssl_verification: true
      person_dn_format: uid=%KEY%,ou=People,dc=example,dc=org
      additional_attributes:
        - shellentitlements
people_data_source: ldap
