#!/bin/bash

if [ -z $GITHUB_HEAD_REF ];
then
    GITHUB_HEAD_REF=$(git rev-parse --abbrev-ref HEAD)
fi

# Get the PR diff
diff=$(git diff origin/main origin/${GITHUB_HEAD_REF})
# See if the PR diff is related to entitlements configs
while IFS='' read -r FILES; do
  echo "${FILES[@]}"
done <<< "$diff"
